const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
const PURCHASE_INIT = "PURCHASE_INIT";

export default {
  PURCHASE_BURGER_SUCCESS,
  PURCHASE_BURGER_FAIL,
  PURCHASE_BURGER_START,
  PURCHASE_INIT
};